spring:
  config:
    import: optional:secrets.yml

  application:
    name: appointment-scheduling-system

  # Database configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/appointments
    driver: org.postgresql.Driver

  # Hibernate and JPA configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT expiration date (1 day)
jwt:
  expirationTime: 86400000

#optional:secrets.yml